Update firehose from upstream

diff --git a/packages/firehose-to-syslog/packaging b/packages/firehose-to-syslog/packaging
--- a/packages/firehose-to-syslog/packaging
+++ b/packages/firehose-to-syslog/packaging
@@ -1,19 +1,12 @@
-set -e # exit immediately if a simple command exits with a non-zero status
-set -u # report the usage of uninitialized variables
-set -x # be verbose
+set -e
 
-REPO_NAME=github.com/cloudfoundry-community/firehose-to-syslog
+mkdir -p ${BOSH_INSTALL_TARGET}/src/github.com/cloudfoundry-community
+mv firehose-to-syslog ${BOSH_INSTALL_TARGET}/src/github.com/cloudfoundry-community
+export GOPATH=$BOSH_INSTALL_TARGET
 
-REPO_DIR=${BOSH_INSTALL_TARGET}/src/${REPO_NAME}
-
-rm -rf $(dirname $REPO_DIR)
-mkdir -p $(dirname $REPO_DIR)
-mkdir -p $BOSH_INSTALL_TARGET/bin
-
-cp -a $(basename $REPO_NAME)/ $REPO_DIR
-
-export GOROOT=$(readlink -nf /var/vcap/packages/golang1.4)
-export GOPATH=$BOSH_INSTALL_TARGET:${REPO_DIR}/Godeps/_workspace
+export GOROOT=$(readlink -nf /var/vcap/packages/golang)
 export PATH=$GOROOT/bin:$PATH
+go install github.com/cloudfoundry-community/firehose-to-syslog
 
-go install $REPO_NAME
+# clean up source artifacts
+rm -rf ${BOSH_INSTALL_TARGET}/src ${BOSH_INSTALL_TARGET}/pkg
